# Generated by Django 3.2.9 on 2021-12-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_shop', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='basket_item',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_shop.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_shop.producttype'),
        ),
    ]
