# Generated by Django 3.2.9 on 2022-01-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='basket_status',
            field=models.CharField(choices=[('chk', 'chk'), ('del', 'delete'), ('vrf', 'verify'), ('act', 'active')], default='chk', max_length=3),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=72, unique=True),
        ),
    ]
