# Generated by Django 3.2.9 on 2022-01-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_shop', '0003_auto_20220107_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='basket_status',
            field=models.CharField(choices=[('chk', 'check'), ('del', 'delete'), ('vrf', 'verify'), ('act', 'active')], default='chk', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.PositiveIntegerField(),
        ),
    ]
