# Generated by Django 3.2.9 on 2021-12-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_shop', '0003_auto_20211229_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
