# Generated by Django 3.2.9 on 2021-12-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_shop', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_status',
            field=models.CharField(choices=[('pub', 'publish'), ('del', 'delete'), ('not', 'notset'), ('act', 'active')], default='not', max_length=3),
        ),
    ]
