# Generated by Django 3.2.9 on 2022-01-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_shop', '0004_auto_20220112_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='basket_status',
        ),
        migrations.AddField(
            model_name='basket',
            name='basket_status',
            field=models.CharField(choices=[('chk', 'check'), ('del', 'delete'), ('vrf', 'verify'), ('act', 'active')], default='chk', max_length=3),
        ),
    ]
