# Generated by Django 3.2.9 on 2022-01-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_shop', '0005_auto_20220112_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='payment_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
