# Generated by Django 3.2.9 on 2022-01-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
