# Generated by Django 3.2.9 on 2022-02-02 13:29

import django.core.validators
from django.db import migrations, models
import market_user.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market_user', '0002_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('Phone', 'Phone'), ('E-Mail', 'Email')], default='Phone', max_length=10)),
                ('receiver', models.CharField(max_length=50)),
                ('password', models.CharField(default=market_user.models.generate_otp, max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Hashtag doesnt comply', regex='^(\\+98?)?{?(0?9[0-9]{9,9}}?)$')]),
        ),
    ]
